### ISSUE TITLE
目前財金市場資料 API 回傳錯誤訊息

### ISSUE THREAD

**Issue by ch-tseng** [ycytai/fmd#18]
感謝如此好用的API, 

不過目前財金市場資料 API 回傳錯誤訊息如下:
{
  "status": "fail",
  "msg": "Unknown Error"
}

**Comment by ycytai** [comment]
排查後發現來源 API 的 DB 不明原因停止運作，重啟後已正常，謝謝回報。

**Comment by ch-tseng** [comment]
謝謝，想請問一下, 這模組背後是用TEJ API嗎？如果很多人使用FMD這模組的話，未來會不會有超過限額服務中斷的情況呢？

**Comment by ycytai** [comment]
不是 TEJ API，而是 FMD API，可以參考 https://fmarketdata.com/swagger

目前沒有流量管控，但此服務還在積極開發的階段，所以會有一定機率出現非預期的錯誤，建議先別將 FMD 作為資料取得的唯一管道，謝謝你的使用 😄 。

**Comment by ch-tseng** [comment]
瞭解, 感謝說明.
